// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "projects-20190910123545-hostingbucket-devc",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://projects-20190910123545-hostingbucket-devc.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:d01021f2-33c5-4c81-8135-45f5886baa9e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6xSztfbfz",
    "aws_user_pools_web_client_id": "5qq4a0gbtc87ce70v4r9dqi56j",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ougo52ihunawhlxdf2qls6yypu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
